### ISSUE TITLE
Integrate autopep8 into the project

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/example-shm#13]
[autopep8](https://pypi.org/project/autopep8/) is a code formatting tool. The configuration can be placed in `pyproject.toml`

```toml
[tool.autopep8]
max_line_length = 120
ignore = "E501,W6"  # or ["E501", "W6"]
in-place = true
recursive = true
aggressive = 3
```
